<?php

$contentDir = realpath(__DIR__ . '/../');
$baseDir = dirname($contentDir);

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `royalcms optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'files' => [
        $baseDir . '/vendor/royalcms/qrcode/Royalcms/Component/QrCode/QrCodeServiceProvider.php',
        $baseDir . '/vendor/royalcms/sms/Royalcms/Component/Sms/SmsServiceProvider.php',
        $baseDir . '/vendor/royalcms/alidayu/Royalcms/Component/Alidayu/AlidayuServiceProvider.php',
        $baseDir . '/vendor/royalcms/image/Royalcms/Component/Image/ImageServiceProvider.php',
        $baseDir . '/vendor/royalcms/ip-address/Royalcms/Component/IpAddress/Ip.php',
        $baseDir . '/vendor/royalcms/class-loader/Royalcms/Component/ClassLoader/ClassManager.php',
        $baseDir . '/vendor/royalcms/purifier/Royalcms/Component/Purifier/PurifierServiceProvider.php',
        $baseDir . '/vendor/royalcms/xml-response/Royalcms/Component/XmlResponse/XmlResponseServiceProvider.php',
        $baseDir . '/vendor/royalcms/excel/Royalcms/Component/Excel/ExcelServiceProvider.php',

        $baseDir . '/vendor/royalcms/model/Royalcms/Component/Model/Database/DatabaseInterface.php',
        $baseDir . '/vendor/royalcms/model/Royalcms/Component/Model/Database/Database.php',
        $baseDir . '/vendor/royalcms/model/Royalcms/Component/Model/Database/Mysqli.php',
        $baseDir . '/vendor/royalcms/model/Royalcms/Component/Model/Database/DatabaseFactory.php',
        $baseDir . '/vendor/royalcms/model/Royalcms/Component/Model/ModelManage.php',
        $baseDir . '/vendor/royalcms/model/Royalcms/Component/Model/Model.php',
        $baseDir . '/vendor/royalcms/model/Royalcms/Component/Model/ViewModel.php',

        $contentDir . '/apps/adsense/classes/AdsenseServiceProvider.php',
        $contentDir . '/apps/affiliate/classes/AffiliateServiceProvider.php',
        $contentDir . '/apps/api/classes/ApiServiceProvider.php',
        $contentDir . '/apps/article/classes/ArticleServiceProvider.php',
        $contentDir . '/apps/bonus/classes/BonusServiceProvider.php',
        $contentDir . '/apps/captcha/classes/CaptchaServiceProvider.php',
        $contentDir . '/apps/cart/classes/CartServiceProvider.php',
        $contentDir . '/apps/cashier/classes/CashierServiceProvider.php',
        $contentDir . '/apps/comment/classes/CommentServiceProvider.php',
        $contentDir . '/apps/connect/classes/ConnectServiceProvider.php',
        $contentDir . '/apps/favourable/classes/FavourableServiceProvider.php',
        $contentDir . '/apps/goods/classes/GoodsServiceProvider.php',
        $contentDir . '/apps/groupbuy/classes/GroupbuyServiceProvider.php',
        $contentDir . '/apps/logviewer/classes/LogviewerServiceProvider.php',
        $contentDir . '/apps/mail/classes/MailServiceProvider.php',
        $contentDir . '/apps/maintain/classes/MaintainServiceProvider.php',
        $contentDir . '/apps/mobile/classes/MobileServiceProvider.php',
        $contentDir . '/apps/orders/classes/OrdersServiceProvider.php',
        $contentDir . '/apps/payment/classes/PaymentServiceProvider.php',
        $contentDir . '/apps/promotion/classes/PromotionServiceProvider.php',
        $contentDir . '/apps/push/classes/PushServiceProvider.php',
        $contentDir . '/apps/setting/classes/SettingServiceProvider.php',
        $contentDir . '/apps/shipping/classes/ShippingServiceProvider.php',
        $contentDir . '/apps/sms/classes/SmsServiceProvider.php',
        $contentDir . '/apps/stats/classes/StatsServiceProvider.php',
        $contentDir . '/apps/user/classes/UserServiceProvider.php',
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */

    'providers' => [
        'Royalcms\Component\Exception\ExceptionServiceProvider',
        'Royalcms\Component\App\AppServiceProvider',
        'Royalcms\Component\Database\DatabaseServiceProvider',
        'Royalcms\Component\NativeSession\NativeSessionServiceProvider',
        'Royalcms\Component\Package\PackageServiceProvider',
        'Royalcms\Component\Redis\RedisServiceProvider',
        'Royalcms\Component\Gettext\GettextServiceProvider',
        'Royalcms\Component\Cache\CacheServiceProvider',
        'Royalcms\Component\Hook\HookServiceProvider',
        'Royalcms\Component\Script\ScriptServiceProvider',
        'Royalcms\Component\Timer\TimerServiceProvider',
        'Royalcms\Component\SmartyView\SmartyCompileServiceProvider',
        'Royalcms\Component\Rewrite\RewriteServiceProvider',
        'Royalcms\Component\Error\ErrorServiceProvider',
        'Royalcms\Component\DefaultRoute\DefaultRouteServiceProvider',
        'Royalcms\Component\Variable\VariableServiceProvider',
        'Royalcms\Component\Repository\RepositoryServiceProvider',
        'Royalcms\Component\Agent\AgentServiceProvider',
        'Royalcms\Component\Storage\StorageServiceProvider',
        'Royalcms\Component\Environment\EnvironmentServiceProvider',
        'Royalcms\Component\Upload\UploadServiceProvider',

        'Ecjia\System\Providers\SystemServiceProvider',

        'Ecjia\Component\Config\ConfigServiceProvider',
        'Ecjia\Component\Framework\EcjiaServiceProvider'
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled Config files, Excludes other config files.
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */
    'exclude_configs' => [
        '*::system',
        '*::namespaces',
        '*::provider',
        '*::facade',
        '*::database',
        '*::cache',
        '*::app',
        '*::session',
        '*::view',
        '*::route',
        '*::site',
        '*::storage',
        '*::queue',
        '*::release',
        '*::pay',
        '*::upload',

        'smarty-view::smarty',
        'excel::export',
    ],

];
