<?php
//
//    ______         ______           __         __         ______
//   /\  ___\       /\  ___\         /\_\       /\_\       /\  __ \
//   \/\  __\       \/\ \____        \/\_\      \/\_\      \/\ \_\ \
//    \/\_____\      \/\_____\     /\_\/\_\      \/\_\      \/\_\ \_\
//     \/_____/       \/_____/     \/__\/_/       \/_/       \/_/ /_/
//
//   上海商创网络科技有限公司
//
//  ---------------------------------------------------------------------------------
//
//   一、协议的许可和权利
//
//    1. 您可以在完全遵守本协议的基础上，将本软件应用于商业用途；
//    2. 您可以在协议规定的约束和限制范围内修改本产品源代码或界面风格以适应您的要求；
//    3. 您拥有使用本产品中的全部内容资料、商品信息及其他信息的所有权，并独立承担与其内容相关的
//       法律义务；
//    4. 获得商业授权之后，您可以将本软件应用于商业用途，自授权时刻起，在技术支持期限内拥有通过
//       指定的方式获得指定范围内的技术支持服务；
//
//   二、协议的约束和限制
//
//    1. 未获商业授权之前，禁止将本软件用于商业用途（包括但不限于企业法人经营的产品、经营性产品
//       以及以盈利为目的或实现盈利产品）；
//    2. 未获商业授权之前，禁止在本产品的整体或在任何部分基础上发展任何派生版本、修改版本或第三
//       方版本用于重新开发；
//    3. 如果您未能遵守本协议的条款，您的授权将被终止，所被许可的权利将被收回并承担相应法律责任；
//
//   三、有限担保和免责声明
//
//    1. 本软件及所附带的文件是作为不提供任何明确的或隐含的赔偿或担保的形式提供的；
//    2. 用户出于自愿而使用本软件，您必须了解使用本软件的风险，在尚未获得商业授权之前，我们不承
//       诺提供任何形式的技术支持、使用担保，也不承担任何因使用本软件而产生问题的相关责任；
//    3. 上海商创网络科技有限公司不对使用本产品构建的商城中的内容信息承担责任，但在不侵犯用户隐
//       私信息的前提下，保留以任何方式获取用户信息及商品信息的权利；
//
//   有关本产品最终用户授权协议、商业授权与技术服务的详细内容，均由上海商创网络科技有限公司独家
//   提供。上海商创网络科技有限公司拥有在不事先通知的情况下，修改授权协议的权力，修改后的协议对
//   改变之日起的新授权用户生效。电子文本形式的授权协议如同双方书面签署的协议一样，具有完全的和
//   等同的法律效力。您一旦开始修改、安装或使用本产品，即被视为完全理解并接受本协议的各项条款，
//   在享有上述条款授予的权力的同时，受到相关的约束和限制。协议许可范围以外的行为，将直接违反本
//   授权协议并构成侵权，我们有权随时终止授权，责令停止损害，并保留追究相关责任的权力。
//
//  ---------------------------------------------------------------------------------
//
/**
 * 插入数据 `ecjia_goods_attr` 商品属性
 */
use Royalcms\Component\Database\Seeder;

class DemoGoodsAttrTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            array(
                'goods_attr_id'         => '2393',
                'goods_id'              => '466',
                'attr_id'               => '884',
                'attr_value'            => '蜜甜珍珠无籽红提',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2394',
                'goods_id'              => '466',
                'attr_id'               => '886',
                'attr_value'            => '智利',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2395',
                'goods_id'              => '466',
                'attr_id'               => '887',
                'attr_value'            => '1kg',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2396',
                'goods_id'              => '466',
                'attr_id'               => '888',
                'attr_value'            => '2016',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2397',
                'goods_id'              => '466',
                'attr_id'               => '889',
                'attr_value'            => '002',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2398',
                'goods_id'              => '466',
                'attr_id'               => '890',
                'attr_value'            => '水果',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2410',
                'goods_id'              => '460',
                'attr_id'               => '884',
                'attr_value'            => '香蕉',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2411',
                'goods_id'              => '460',
                'attr_id'               => '886',
                'attr_value'            => '菲律宾',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2412',
                'goods_id'              => '460',
                'attr_id'               => '887',
                'attr_value'            => '约1.5kg',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2413',
                'goods_id'              => '460',
                'attr_id'               => '888',
                'attr_value'            => '2016',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2414',
                'goods_id'              => '460',
                'attr_id'               => '889',
                'attr_value'            => '004',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2415',
                'goods_id'              => '460',
                'attr_id'               => '890',
                'attr_value'            => '水果',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2427',
                'goods_id'              => '461',
                'attr_id'               => '884',
                'attr_value'            => '龙眼',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2428',
                'goods_id'              => '461',
                'attr_id'               => '886',
                'attr_value'            => '泰国',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2429',
                'goods_id'              => '461',
                'attr_id'               => '887',
                'attr_value'            => '2KG装',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2430',
                'goods_id'              => '461',
                'attr_id'               => '888',
                'attr_value'            => '2016',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2431',
                'goods_id'              => '461',
                'attr_id'               => '889',
                'attr_value'            => '006',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2432',
                'goods_id'              => '461',
                'attr_id'               => '890',
                'attr_value'            => '水果',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2433',
                'goods_id'              => '468',
                'attr_id'               => '884',
                'attr_value'            => '青蛇果20个',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2434',
                'goods_id'              => '468',
                'attr_id'               => '886',
                'attr_value'            => '法国',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2435',
                'goods_id'              => '468',
                'attr_id'               => '887',
                'attr_value'            => '约190g/个',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2436',
                'goods_id'              => '468',
                'attr_id'               => '888',
                'attr_value'            => '2016',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2437',
                'goods_id'              => '468',
                'attr_id'               => '889',
                'attr_value'            => '007',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2438',
                'goods_id'              => '468',
                'attr_id'               => '890',
                'attr_value'            => '水果',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2439',
                'goods_id'              => '433',
                'attr_id'               => '884',
                'attr_value'            => '凤梨2个',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2440',
                'goods_id'              => '433',
                'attr_id'               => '886',
                'attr_value'            => '菲律宾',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2441',
                'goods_id'              => '433',
                'attr_id'               => '887',
                'attr_value'            => '200g',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2442',
                'goods_id'              => '433',
                'attr_id'               => '888',
                'attr_value'            => '2016',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2443',
                'goods_id'              => '433',
                'attr_id'               => '889',
                'attr_value'            => '008',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2444',
                'goods_id'              => '433',
                'attr_id'               => '890',
                'attr_value'            => '水果',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2445',
                'goods_id'              => '395',
                'attr_id'               => '884',
                'attr_value'            => '精品红霞草莓32粒',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2446',
                'goods_id'              => '395',
                'attr_id'               => '886',
                'attr_value'            => '中国',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2447',
                'goods_id'              => '395',
                'attr_id'               => '887',
                'attr_value'            => '约30g/个',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2448',
                'goods_id'              => '395',
                'attr_id'               => '888',
                'attr_value'            => '2016',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2449',
                'goods_id'              => '395',
                'attr_id'               => '889',
                'attr_value'            => '008',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2450',
                'goods_id'              => '395',
                'attr_id'               => '890',
                'attr_value'            => '水果',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2457',
                'goods_id'              => '393',
                'attr_id'               => '884',
                'attr_value'            => '红心火龙果',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2458',
                'goods_id'              => '393',
                'attr_id'               => '886',
                'attr_value'            => '越南',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2459',
                'goods_id'              => '393',
                'attr_id'               => '887',
                'attr_value'            => '2.5kg',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2460',
                'goods_id'              => '393',
                'attr_id'               => '888',
                'attr_value'            => '2016',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2461',
                'goods_id'              => '393',
                'attr_id'               => '889',
                'attr_value'            => '010',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2462',
                'goods_id'              => '393',
                'attr_id'               => '890',
                'attr_value'            => '水果',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2468',
                'goods_id'              => '617',
                'attr_id'               => '893',
                'attr_value'            => '精选菜薹',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2469',
                'goods_id'              => '617',
                'attr_id'               => '894',
                'attr_value'            => '中国',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2470',
                'goods_id'              => '617',
                'attr_id'               => '895',
                'attr_value'            => '300g',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2471',
                'goods_id'              => '617',
                'attr_id'               => '896',
                'attr_value'            => '2016',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '2472',
                'goods_id'              => '617',
                'attr_id'               => '897',
                'attr_value'            => '蔬菜',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3864',
                'goods_id'              => '1082',
                'attr_id'               => '884',
                'attr_value'            => '美国加州花色恐龙蛋',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3865',
                'goods_id'              => '1082',
                'attr_id'               => '886',
                'attr_value'            => '美国',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3866',
                'goods_id'              => '1082',
                'attr_id'               => '887',
                'attr_value'            => '3.3kg',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3867',
                'goods_id'              => '1082',
                'attr_id'               => '888',
                'attr_value'            => '2106-10-28',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3868',
                'goods_id'              => '1082',
                'attr_id'               => '889',
                'attr_value'            => '61510',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3869',
                'goods_id'              => '1082',
                'attr_id'               => '890',
                'attr_value'            => '李',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3870',
                'goods_id'              => '1082',
                'attr_id'               => '891',
                'attr_value'            => '上海',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3983',
                'goods_id'              => '1103',
                'attr_id'               => '884',
                'attr_value'            => '温馨祝福鲜果礼盒',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3984',
                'goods_id'              => '1103',
                'attr_id'               => '886',
                'attr_value'            => '中国',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3985',
                'goods_id'              => '1103',
                'attr_id'               => '887',
                'attr_value'            => '15kg',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3986',
                'goods_id'              => '1103',
                'attr_id'               => '888',
                'attr_value'            => '2016-10-29',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3987',
                'goods_id'              => '1103',
                'attr_id'               => '889',
                'attr_value'            => '2160723102',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3988',
                'goods_id'              => '1103',
                'attr_id'               => '890',
                'attr_value'            => '礼品 果篮',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '3989',
                'goods_id'              => '1103',
                'attr_id'               => '891',
                'attr_value'            => '上海',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '4032',
                'goods_id'              => '1046',
                'attr_id'               => '884',
                'attr_value'            => '陕西富士苹果',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '4033',
                'goods_id'              => '1046',
                'attr_id'               => '886',
                'attr_value'            => '陕西',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '4034',
                'goods_id'              => '1046',
                'attr_id'               => '887',
                'attr_value'            => '5kg',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '4035',
                'goods_id'              => '1046',
                'attr_id'               => '888',
                'attr_value'            => '2016-11-01',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '4036',
                'goods_id'              => '1046',
                'attr_id'               => '889',
                'attr_value'            => '2161025101',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '4037',
                'goods_id'              => '1046',
                'attr_id'               => '890',
                'attr_value'            => '苹果',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
            array(
                'goods_attr_id'         => '4038',
                'goods_id'              => '1046',
                'attr_id'               => '891',
                'attr_value'            => '上海',
                'color_value'           => '',
                'attr_price'            => '0',
                'attr_sort'             => '0',
                'attr_img_flie'         => '',
                'attr_gallery_flie'     => '',
                'attr_img_site'         => '',
                'attr_checked'          => '0',
            ),
        );

        RC_DB::table('goods_attr')->truncate();
        RC_DB::table('goods_attr')->insert($data);
    }
}