<?php
//
//    ______         ______           __         __         ______
//   /\  ___\       /\  ___\         /\_\       /\_\       /\  __ \
//   \/\  __\       \/\ \____        \/\_\      \/\_\      \/\ \_\ \
//    \/\_____\      \/\_____\     /\_\/\_\      \/\_\      \/\_\ \_\
//     \/_____/       \/_____/     \/__\/_/       \/_/       \/_/ /_/
//
//   上海商创网络科技有限公司
//
//  ---------------------------------------------------------------------------------
//
//   一、协议的许可和权利
//
//    1. 您可以在完全遵守本协议的基础上，将本软件应用于商业用途；
//    2. 您可以在协议规定的约束和限制范围内修改本产品源代码或界面风格以适应您的要求；
//    3. 您拥有使用本产品中的全部内容资料、商品信息及其他信息的所有权，并独立承担与其内容相关的
//       法律义务；
//    4. 获得商业授权之后，您可以将本软件应用于商业用途，自授权时刻起，在技术支持期限内拥有通过
//       指定的方式获得指定范围内的技术支持服务；
//
//   二、协议的约束和限制
//
//    1. 未获商业授权之前，禁止将本软件用于商业用途（包括但不限于企业法人经营的产品、经营性产品
//       以及以盈利为目的或实现盈利产品）；
//    2. 未获商业授权之前，禁止在本产品的整体或在任何部分基础上发展任何派生版本、修改版本或第三
//       方版本用于重新开发；
//    3. 如果您未能遵守本协议的条款，您的授权将被终止，所被许可的权利将被收回并承担相应法律责任；
//
//   三、有限担保和免责声明
//
//    1. 本软件及所附带的文件是作为不提供任何明确的或隐含的赔偿或担保的形式提供的；
//    2. 用户出于自愿而使用本软件，您必须了解使用本软件的风险，在尚未获得商业授权之前，我们不承
//       诺提供任何形式的技术支持、使用担保，也不承担任何因使用本软件而产生问题的相关责任；
//    3. 上海商创网络科技有限公司不对使用本产品构建的商城中的内容信息承担责任，但在不侵犯用户隐
//       私信息的前提下，保留以任何方式获取用户信息及商品信息的权利；
//
//   有关本产品最终用户授权协议、商业授权与技术服务的详细内容，均由上海商创网络科技有限公司独家
//   提供。上海商创网络科技有限公司拥有在不事先通知的情况下，修改授权协议的权力，修改后的协议对
//   改变之日起的新授权用户生效。电子文本形式的授权协议如同双方书面签署的协议一样，具有完全的和
//   等同的法律效力。您一旦开始修改、安装或使用本产品，即被视为完全理解并接受本协议的各项条款，
//   在享有上述条款授予的权力的同时，受到相关的约束和限制。协议许可范围以外的行为，将直接违反本
//   授权协议并构成侵权，我们有权随时终止授权，责令停止损害，并保留追究相关责任的权力。
//
//  ---------------------------------------------------------------------------------
//
/**
 * 插入数据 `ecjia_ad` 广告(结束时间2027-1-1)
 */
use Royalcms\Component\Database\Seeder;

class InitAdTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
        	array(
        		'ad_id'        => '133',
        	    'position_id'  => '98',
        	    'media_type'   => '0',
        	    'ad_name'      => '移动首页广告组2.1',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1033',
        	    'ad_code'      => 'data/afficheimg/1470682423300753249.png',
        	    'start_time'   => '1452758400',
        	    'end_time'     => '1538208000',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '137',
        	    'position_id'  => '97',
        	    'media_type'   => '0',
        	    'ad_name'      => '移动首页广告组3.1',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1078',
        	    'ad_code'      => 'data/afficheimg/1480630295423978066.png',
        	    'start_time'   => '1476691200',
        	    'end_time'     => '1509350400',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '138',
        	    'position_id'  => '97',
        	    'media_type'   => '0',
        	    'ad_name'      => '移动首页广告组3.2',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_detail&goods_id=653',
        	    'ad_code'      => 'data/afficheimg/1477679946715276347.png',
        	    'start_time'   => '1476172800',
        	    'end_time'     => '1501142400',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '139',
        	    'position_id'  => '97',
        	    'media_type'   => '0',
        	    'ad_name'      => '移动首页广告组3.3',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_detail&goods_id=1039',
        	    'ad_code'      => 'data/afficheimg/1477679969238922905.png',
        	    'start_time'   => '1476432000',
        	    'end_time'     => '1496131200',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '140',
        	    'position_id'  => '97',
        	    'media_type'   => '0',
        	    'ad_name'      => '移动首页广告组3.4',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_detail&goods_id=311',
        	    'ad_code'      => 'data/afficheimg/1477679989058885859.png',
        	    'start_time'   => '1452758400',
        	    'end_time'     => '1501228800',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '150',
        	    'position_id'  => '102',
        	    'media_type'   => '0',
        	    'ad_name'      => '开机广告',
        	    'ad_link'      => 'ecjiaopen://app?open_type=main',
        	    'ad_code'      => 'data/afficheimg/1477702016525679059.png',
        	    'start_time'   => '1475654400',
        	    'end_time'     => '1498723200',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '153',
        	    'position_id'  => '106',
        	    'media_type'   => '0',
        	    'ad_name'      => '分类1',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1032',
        	    'ad_code'      => 'data/category/1459454069433195862.png',
        	    'start_time'   => '1491465600',
        	    'end_time'     => '1522396800',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '154',
        	    'position_id'  => '107',
        	    'media_type'   => '0',
        	    'ad_name'      => '分类2',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1047',
        	    'ad_code'      => 'data/category/1459458216777256123.png',
        	    'start_time'   => '1491465600',
        	    'end_time'     => '1519718400',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '155',
        	    'position_id'  => '108',
        	    'media_type'   => '0',
        	    'ad_name'      => '分类3',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1064',
        	    'ad_code'      => 'data/category/1459465496683224975.png',
        	    'start_time'   => '1491465600',
        	    'end_time'     => '1524988800',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '156',
        	    'position_id'  => '109',
        	    'media_type'   => '0',
        	    'ad_name'      => '分类4',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1078',
        	    'ad_code'      => 'data/category/1459461890866804359.png',
        	    'start_time'   => '1491465600',
        	    'end_time'     => '1527667200',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '157',
        	    'position_id'  => '110',
        	    'media_type'   => '0',
        	    'ad_name'      => '分类5',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1092',
        	    'ad_code'      => 'data/category/1459460778180533114.png',
        	    'start_time'   => '1491465600',
        	    'end_time'     => '1514620800',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '158',
        	    'position_id'  => '111',
        	    'media_type'   => '0',
        	    'ad_name'      => '分类6',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1114',
        	    'ad_code'      => 'data/category/1459460131280159213.png',
        	    'start_time'   => '1491465600',
        	    'end_time'     => '1524988800',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '159',
        	    'position_id'  => '112',
        	    'media_type'   => '0',
        	    'ad_name'      => '分类7',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1135',
        	    'ad_code'      => 'data/category/1459461396005330093.png',
        	    'start_time'   => '1491465600',
        	    'end_time'     => '1514620800',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '160',
        	    'position_id'  => '113',
        	    'media_type'   => '0',
        	    'ad_name'      => '分类8',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1167',
        	    'ad_code'      => 'data/category/1459462285259394728.png',
        	    'start_time'   => '1491465600',
        	    'end_time'     => '1522310400',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '161',
        	    'position_id'  => '114',
        	    'media_type'   => '0',
        	    'ad_name'      => '分类9',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1186',
        	    'ad_code'      => 'data/category/1459462895864322155.png',
        	    'start_time'   => '1491465600',
        	    'end_time'     => '1522310400',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '162',
        	    'position_id'  => '115',
        	    'media_type'   => '0',
        	    'ad_name'      => '分类10',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1240',
        	    'ad_code'      => 'data/category/1459464791734452461.jpg',
        	    'start_time'   => '1491465600',
        	    'end_time'     => '1532937600',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '163',
        	    'position_id'  => '116',
        	    'media_type'   => '0',
        	    'ad_name'      => '',
        	    'ad_link'      => 'https://cityo2o.ecjia.com/index.php?m=merchant&c=store&a=category&cat_id=4',
        	    'ad_code'      => 'data/cycleimage/1492650806593974463.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '8',
        	),
        	array(
        		'ad_id'        => '164',
        	    'position_id'  => '116',
        	    'media_type'   => '0',
        	    'ad_name'      => '',
        	    'ad_link'      => 'https://cityo2o.ecjia.com/index.php?m=merchant&c=goods&a=init&store_id=111',
        	    'ad_code'      => 'data/cycleimage/1492651290525993731.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '8',
        	),
        	array(
        		'ad_id'        => '165',
        	    'position_id'  => '116',
        	    'media_type'   => '0',
        	    'ad_name'      => '',
        	    'ad_link'      => 'https://cityo2o.ecjia.com/index.php?m=merchant&c=goods&a=init&store_id=60',
        	    'ad_code'      => 'data/cycleimage/1492651307128656813.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '8',
        	),
        	array(
        		'ad_id'        => '166',
        	    'position_id'  => '116',
        	    'media_type'   => '0',
        	    'ad_name'      => '',
        	    'ad_link'      => 'https://cityo2o.ecjia.com/index.php?m=merchant&c=goods&a=init&store_id=109',
        	    'ad_code'      => 'data/cycleimage/1492651334051472978.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '8',
        	),
        	array(
        		'ad_id'        => '167',
        	    'position_id'  => '116',
        	    'media_type'   => '0',
        	    'ad_name'      => '',
        	    'ad_link'      => 'https://cityo2o.ecjia.com/index.php?m=goods&c=index&a=init&cat_id=1033',
        	    'ad_code'      => 'data/cycleimage/1492651353919196607.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '8',
        	),
        	array(
        		'ad_id'        => '168',
        	    'position_id'  => '116',
        	    'media_type'   => '0',
        	    'ad_name'      => 'm',
        	    'ad_link'      => 'https://ecjia.com/o2o.html',
        	    'ad_code'      => 'data/afficheimg/banner1.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '1',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '169',
        	    'position_id'  => '116',
        	    'media_type'   => '0',
        	    'ad_name'      => 'm',
        	    'ad_link'      => 'https://ecjia.com',
        	    'ad_code'      => 'data/afficheimg/banner2.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '170',
        	    'position_id'  => '116',
        	    'media_type'   => '0',
        	    'ad_name'      => 'm',
        	    'ad_link'      => 'https://ecjia.com/wiki/%E5%B8%AE%E5%8A%A9:ECJia%E5%88%B0%E5%AE%B6',
        	    'ad_code'      => 'data/afficheimg/banner3.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '171',
        	    'position_id'  => '116',
        	    'media_type'   => '0',
        	    'ad_name'      => 'm',
        	    'ad_link'      => 'http://www.ecmoban.com/',
        	    'ad_code'      => 'data/afficheimg/banner4.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '172',
        	    'position_id'  => '116',
        	    'media_type'   => '0',
        	    'ad_name'      => 'm',
        	    'ad_link'      => 'http://www.dscmall.cn/',
        	    'ad_code'      => 'data/afficheimg/banner5.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
            array(
                'ad_id'        => '173',
                'position_id'  => '118',
                'media_type'   => '0',
                'ad_name'      => '',
                'ad_link'      => 'https://cityo2o.ecjia.com/index.php?m=merchant&c=store&a=category',
                'ad_code'      => 'data/cycleimage/1492650692097234468.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '50',
                'show_client'  => '8',
            ),
        	array(
        		'ad_id'        => '183',
        	    'position_id'  => '122',
        	    'media_type'   => '0',
        	    'ad_name'      => '水果蔬菜',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1032',
        	    'ad_code'      => 'data/shortcut/1477700183823048386.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '0',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '184',
        	    'position_id'  => '122',
        	    'media_type'   => '0',
        	    'ad_name'      => '肉禽蛋奶',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1047',
        	    'ad_code'      => 'data/shortcut/1477700190620505129.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '1',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '185',
        	    'position_id'  => '122',
        	    'media_type'   => '0',
        	    'ad_name'      => '冷热速食',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1064',
        	    'ad_code'      => 'data/shortcut/1477700197732149350.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '2',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '186',
        	    'position_id'  => '122',
        	    'media_type'   => '0',
        	    'ad_name'      => '休闲食品',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1078',
        	    'ad_code'      => 'data/shortcut/1477700204215089751.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '3',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '187',
        	    'position_id'  => '122',
        	    'media_type'   => '0',
        	    'ad_name'      => '酒水饮料',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1092',
        	    'ad_code'      => 'data/shortcut/1477700210378659761.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '4',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '188',
        	    'position_id'  => '122',
        	    'media_type'   => '0',
        	    'ad_name'      => '粮油调味',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1114',
        	    'ad_code'      => 'data/shortcut/1477700217181679112.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '5',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '189',
        	    'position_id'  => '122',
        	    'media_type'   => '0',
        	    'ad_name'      => '清洁日化',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1135',
        	    'ad_code'      => 'data/shortcut/1477700223890846471.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '6',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '190',
        	    'position_id'  => '122',
        	    'media_type'   => '0',
        	    'ad_name'      => '家居用品',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1167',
        	    'ad_code'      => 'data/shortcut/1477700537011530251.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '7',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '191',
        	    'position_id'  => '122',
        	    'media_type'   => '0',
        	    'ad_name'      => '鲜花蛋糕',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1186',
        	    'ad_code'      => 'data/shortcut/1477700617184169592.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '8',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '192',
        	    'position_id'  => '122',
        	    'media_type'   => '0',
        	    'ad_name'      => '上门服务',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_seller_list&category_id=1240',
        	    'ad_code'      => 'data/shortcut/1478221589448573017.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '50',
        	    'show_client'  => '7',
        	),
        	array(
        		'ad_id'        => '196',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '首页',
        	    'ad_link'      => 'ecjiaopen://app?open_type=main',
        	    'ad_code'      => 'data/shortcut/1493936135555123394.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '15',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '197',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '订单',
        	    'ad_link'      => 'ecjiaopen://app?open_type=orders_list',
        	    'ad_code'      => 'data/shortcut/1493936201944514882.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '17',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '198',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '订单详情',
        	    'ad_link'      => 'ecjiaopen://app?open_type=orders_detail&order_id=4119',
        	    'ad_code'      => 'data/shortcut/1493936236718514151.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '18',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '199',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '收货地址',
        	    'ad_link'      => 'ecjiaopen://app?open_type=user_address',
        	    'ad_code'      => 'data/shortcut/1493936269076633694.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '19',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '200',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '帮助中心',
        	    'ad_link'      => 'ecjiaopen://app?open_type=help',
        	    'ad_code'      => 'data/shortcut/1493936305003991267.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '20',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '201',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '二维码分享',
        	    'ad_link'      => 'ecjiaopen://app?open_type=qrshare',
        	    'ad_code'      => 'data/shortcut/1493936356030437932.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '21',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '202',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '用户中心',
        	    'ad_link'      => 'ecjiaopen://app?open_type=user_center',
        	    'ad_code'      => 'data/shortcut/1493936397540575049.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '21',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '203',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '浏览历史',
        	    'ad_link'      => 'ecjiaopen://app?open_type=history',
        	    'ad_code'      => 'data/shortcut/1493936449412004730.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '23',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '204',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '商品评论',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_comment&goods_id=95',
        	    'ad_code'      => 'data/shortcut/1493936483966647376.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '0',
        	    'sort_order'   => '24',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '206',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '商品详情',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_detail&goods_id=1180',
        	    'ad_code'      => 'data/shortcut/1493936575940537708.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '26',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '207',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '二维码扫描',
        	    'ad_link'      => 'ecjiaopen://app?open_type=qrcode',
        	    'ad_code'      => 'data/shortcut/1493936615367458534.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '27',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '208',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '搜索',
        	    'ad_link'      => 'ecjiaopen://app?open_type=search&keyword=apple',
        	    'ad_code'      => 'data/shortcut/1493936664584830334.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '28',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '209',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '消息中心',
        	    'ad_link'      => 'ecjiaopen://app?open_type=message',
        	    'ad_code'      => 'data/shortcut/1493936724759420467.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '29',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '211',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '钱包',
        	    'ad_link'      => 'ecjiaopen://app?open_type=user_wallet',
        	    'ad_code'      => 'data/shortcut/1493936809550368618.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '32',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '212',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '地图',
        	    'ad_link'      => 'ecjiaopen://app?open_type=map',
        	    'ad_code'      => 'data/shortcut/1493936851929038027.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '33',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '213',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '购物车',
        	    'ad_link'      => 'ecjiaopen://app?open_type=cart',
        	    'ad_code'      => 'data/shortcut/1493936881718554621.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '33',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '214',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '我的余额',
        	    'ad_link'      => 'ecjiaopen://app?open_type=user_account',
        	    'ad_code'      => 'data/shortcut/1493936932839547420.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '34',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '215',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '设置',
        	    'ad_link'      => 'ecjiaopen://app?open_type=setting',
        	    'ad_code'      => 'data/shortcut/1493936969900627172.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '34',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '216',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '注册',
        	    'ad_link'      => 'pen://app?open_type=sign_up',
        	    'ad_code'      => 'data/shortcut/1493937013731630394.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '35',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '217',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '文章',
        	    'ad_link'      => 'https://cityo2o.ecjia.com/index.php?m=article&c=mobile&a=info&id=109',
        	    'ad_code'      => 'data/shortcut/1493937060524160120.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '39',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '218',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '促销商品',
        	    'ad_link'      => 'ecjiaopen://app?open_type=goods_suggest&type=promotion',
        	    'ad_code'      => 'data/shortcut/1493937101463797694.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '40',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '219',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => 'EC+到家简介',
        	    'ad_link'      => 'https://ecjia.com/o2o.html',
        	    'ad_code'      => 'data/shortcut/1493937297749128340.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '0',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '220',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '到家视频介绍',
        	    'ad_link'      => 'https://dn-ecmoban.qbox.me/ECJIAo2o-rwxf.mp4',
        	    'ad_code'      => 'data/shortcut/1493937331496110512.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '0',
        	    'sort_order'   => '1',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '221',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '常见问题',
        	    'ad_link'      => 'https://ecjia.com/wiki/常见问题',
        	    'ad_code'      => 'data/shortcut/1493937361474592575.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '2',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '222',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '免责声明',
        	    'ad_link'      => 'https://ecjia.com/readme/disclaimer.html',
        	    'ad_code'      => 'data/shortcut/1493937400288759209.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '0',
        	    'sort_order'   => '3',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '223',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '地址',
        	    'ad_link'      => 'ecjiaopen://app?open_type=user_address',
        	    'ad_code'      => 'data/shortcut/1493937428305739494.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '4',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '224',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '订单',
        	    'ad_link'      => 'ecjiaopen://app?open_type=orders_list',
        	    'ad_code'      => 'data/shortcut/1493937466305740518.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '0',
        	    'sort_order'   => '4',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '225',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '会员专享',
        	    'ad_link'      => 'https://ecjia.com/readme/disclaimer.html',
        	    'ad_code'      => 'data/shortcut/1493937497139732725.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '0',
        	    'sort_order'   => '4',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '226',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => 'ec+官网',
        	    'ad_link'      => 'https://ecjia.com',
        	    'ad_code'      => 'data/shortcut/1493937538760841476.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '1',
        	    'sort_order'   => '5',
        	    'show_client'  => '3',
        	),
        	array(
        		'ad_id'        => '227',
        	    'position_id'  => '123',
        	    'media_type'   => '0',
        	    'ad_name'      => '二维码扫描',
        	    'ad_link'      => 'ecjiaopen://app?open_type=qrcode',
        	    'ad_code'      => 'data/shortcut/1493937575656087983.png',
        	    'start_time'   => '0',
        	    'end_time'     => '0',
        	    'click_count'  => '0',
        	    'enabled'      => '0',
        	    'sort_order'   => '9',
        	    'show_client'  => '3',
        	),
            array(
                'ad_id'        => '228',
                'position_id'  => '123',
                'media_type'   => '0',
                'ad_name'      => '意见反馈',
                'ad_link'      => 'ecjiaopen://app?open_type=groupbuy',
                'ad_code'      => 'data/shortcut/1493937622234440643.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '0',
                'sort_order'   => '11',
                'show_client'  => '3',
            ),
            array(
                'ad_id'        => '229',
                'position_id'  => '123',
                'media_type'   => '0',
                'ad_name'      => 'ECJia到家帮助',
                'ad_link'      => 'https://ecjia.com/wiki/帮助:ECJia到家',
                'ad_code'      => 'data/shortcut/1493938174856633281.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '11',
                'show_client'  => '3',
            ),
            array(
                'ad_id'        => '230',
                'position_id'  => '123',
                'media_type'   => '0',
                'ad_name'      => '咨询',
                'ad_link'      => 'ecjiaopen://app?open_type=feedback',
                'ad_code'      => 'data/shortcut/1493937694727747746.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '0',
                'sort_order'   => '12',
                'show_client'  => '3',
            ),
            array(
                'ad_id'        => '231',
                'position_id'  => '123',
                'media_type'   => '0',
                'ad_name'      => '帮助中心',
                'ad_link'      => 'ecjiaopen://app?open_type=help',
                'ad_code'      => 'data/shortcut/1493937741148777720.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '13',
                'show_client'  => '3',
            ),
            array(
                'ad_id'        => '232',
                'position_id'  => '123',
                'media_type'   => '0',
                'ad_name'      => '店铺首页',
                'ad_link'      => 'ecjiaopen://app?open_type=merchant&merchant_id=58',
                'ad_code'      => 'data/shortcut/1493939246959136407.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '38',
                'show_client'  => '3',
            ),
            array(
                'ad_id'        => '233',
                'position_id'  => '123',
                'media_type'   => '0',
                'ad_name'      => '用户红包',
                'ad_link'      => 'ecjiaopen://app?open_type=user_bonus&type=usable',
                'ad_code'      => 'data/shortcut/1493939078187195246.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '42',
                'show_client'  => '3',
            ),
            array(
                'ad_id'        => '234',
                'position_id'  => '123',
                'media_type'   => '0',
                'ad_name'      => '商品分类',
                'ad_link'      => 'ecjiaopen://app?open_type=category_list',
                'ad_code'      => 'data/shortcut/1493939142184051151.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '43',
                'show_client'  => '3',
            ),
            array(
                'ad_id'        => '235',
                'position_id'  => '123',
                'media_type'   => '0',
                'ad_name'      => '找回密码',
                'ad_link'      => 'ecjiaopen://app?open_type=forget_password',
                'ad_code'      => 'data/shortcut/1493939491414553635.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '37',
                'show_client'  => '3',
            ),
            array(
                'ad_id'        => '236',
                'position_id'  => '123',
                'media_type'   => '0',
                'ad_name'      => '修改密码',
                'ad_link'      => 'ecjiaopen://app?open_type=user_password',
                'ad_code'      => 'data/shortcut/1493939515102335687.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '38',
                'show_client'  => '3',
            ),
            array(
                'ad_id'        => '237',
                'position_id'  => '123',
                'media_type'   => '0',
                'ad_name'      => '登录',
                'ad_link'      => 'ecjiaopen://app?open_type=sign_in',
                'ad_code'      => 'data/shortcut/1493940105685464475.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '0',
                'sort_order'   => '35',
                'show_client'  => '3',
            ),
            
            array(
                'ad_id'        => '238',
                'position_id'  => '124',
                'media_type'   => '0',
                'ad_name'      => '',
                'ad_link'      => 'https://ecjia.com/download.html',
                'ad_code'      => 'data/cycleimage/1496342092378279633.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '50',
                'show_client'  => '7',
            ),
            array(
                'ad_id'        => '239',
                'position_id'  => '124',
                'media_type'   => '0',
                'ad_name'      => '',
                'ad_link'      => 'https://mp.weixin.qq.com/s?__biz=MzA5MjcwMzU0MQ==&idx=2&mid=2247483774&sn=6a467a8912156ec70b648f4bd167b44d',
                'ad_code'      => 'data/cycleimage/1496342134992478693.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '50',
                'show_client'  => '7',
            ),
            array(
                'ad_id'        => '240',
                'position_id'  => '124',
                'media_type'   => '0',
                'ad_name'      => '',
                'ad_link'      => 'https://mp.weixin.qq.com/s?__biz=MzA5MjcwMzU0MQ==&mid=2247483769&idx=2&sn=115250bee8f874e095dcea7f71a50889',
                'ad_code'      => 'data/cycleimage/1496342191006151668.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '50',
                'show_client'  => '7',
            ),
            array(
                'ad_id'        => '241',
                'position_id'  => '124',
                'media_type'   => '0',
                'ad_name'      => '',
                'ad_link'      => 'https://mp.weixin.qq.com/s?__biz=MzA5MjcwMzU0MQ==&mid=2247483769&idx=3&sn=9bbf280fcdad31eff45fb7bf6b05f37a',
                'ad_code'      => 'data/cycleimage/1496342278158792453.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '50',
                'show_client'  => '7',
            ),
            array(
                'ad_id'        => '242',
                'position_id'  => '124',
                'media_type'   => '0',
                'ad_name'      => '',
                'ad_link'      => 'http://www.ecmoban.com/goods-795.html',
                'ad_code'      => 'data/cycleimage/1496342328783842332.png',
                'start_time'   => '0',
                'end_time'     => '0',
                'click_count'  => '0',
                'enabled'      => '1',
                'sort_order'   => '50',
                'show_client'  => '7',
            ),
        );
        
        RC_DB::table('ad')->truncate();
        RC_DB::table('ad')->insert($data);
    }
    
}